- hosts: all
  become: true
  become_method: sudo
  vars:
    galera_cluster_name: demo_mariadb_cluster
    galera_root_password: your_mariadb_root_password

  tasks:
# install galera cluster package
  - name: installing mariadb-server-galera
    dnf:
      name: '{{item}}'
      state: installed
    with items:
      - mariadb-server-galera
    when: "'haproxy_servers' in group_names"

# if Firewalld is running, allow ports

  - name: add service to firewalld
    firewalld:
      service: mysql
      permanent: yes
      state: enabled
    when: "'haproxy_servers' in group_names"

# reload Firewalld

  - name: Reload service firewalld, in all cases
    ansible.builtin.systemd:
      name: firewalld
      state: reloaded
    when: "'haproxy_servers' in group_names"

# replace config file for deploying galera cluster

