- hosts: all
  become: true
  become_method: sudo

  tasks:
# install haproxy package
  - name: installing haproxy
    dnf:
      name: '{{item}}'
      state: installed
    with items:
      - haproxy
    when: "'haproxy_servers' in group_names"

# set permissive mode for SELinux

  - name: Set permissive mode
    ansible.posix.selinux:
      state: permissive
      policy: targeted
    when: "'haproxy_servers' in group_names"

#Create config file for haproxy

  - name: Create zabbix .cfg file
    template:
      src: haproxy_balancer_config.j2
      dest: /etc/haproxy/haproxy.cfg
      force: yes
    when: "'haproxy_servers' in group_names"

# if Firewalld is running, allow ports

  - name: add active ports
    firewalld:
      service: mysql
      permanent: yes
      state: enabled
    when: "'haproxy_servers' in group_names"

#restart firewalld for change parameters
  - name: Reload service firewalld, in all cases
    ansible.builtin.systemd:
      name: firewalld
      state: reloaded
    when: "'haproxy_servers' in group_names"

#reload service haproxy for the end of installation

  - name: Reload service haproxy
        ansible.builtin.systemd:
          name: haproxy
          state: reloaded
        when: "'haproxy_servers' in group_names"


