- hosts: all
  become: true
  become_method: sudo
  vars:
    mysql_cluster_name: demo_mysql_cluster
    mysql_root_password: your_mysql_root_password

  tasks:
# install galera cluster package
  - name: installing mariadb-server-galera
    dnf:
      name: '{{item}}'
      state: installed
    with items:
      - mariadb-server-galera
    when: "'galera_nodes' in group_names"

# if Firewalld is running, allow ports

  - name: add active ports
    firewalld:
      port: 3306/tcp,4444/tcp,4567-4568/tcp
      permanent: true
      state: enabled
    when: "'galera_nodes' in group_names"

# reload Firewalld

  - name: Reload service firewalld, in all cases
    ansible.builtin.systemd:
      name: firewalld
      state: reloaded
    when: "'galera_nodes' in group_names"

# replace config file for deploying galera cluster

  - name: Create galera .cnf file
    template:
      src: galera_cluster_config.j2
      dest: /etc/my.cnf.d/galera.cnf
    when: "'galera_nodes' in group_names"

# start galera cluster nodes for cluster is up!

  - name: enable service mariadb
      ansible.builtin.systemd:
        name: mariadb.service
        state: started
        enabled: yes

